<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <SelfContained>false</SelfContained>
    <Version>0.14.2</Version>
    <AssemblyVersion>0.14.2.0</AssemblyVersion>
    <FileVersion>0.14.2.0</FileVersion>
  </PropertyGroup>
</Project>
